import tkinter
from tkinter import *
window=Tk()
strvar=StringVar()
strvar1=StringVar()
strvar2=StringVar()
strvar3=StringVar()
strvar4=StringVar()
strvar5=StringVar()
strvar6=StringVar()
strvar7=StringVar()
salary=StringVar()
PT=StringVar()
leave=StringVar()
paid=StringVar()
P2=StringVar()
P3=StringVar()
P4=StringVar()
P5=StringVar()
P6=StringVar()
P7=StringVar()
P8=StringVar()
P9=StringVar()
P10=StringVar()
P11=StringVar()
P12=StringVar()
total_sal=StringVar()
def Employee_Details():
    name=EmployeeFullName.get()
    strvar.set(name)
    Number=EmployeePhNumber.get()
    strvar1.set(Number)
    Department=EmployeeDepartment.get()
    strvar2.set(Department)
    Experience=EmployeeExperience.get()
    strvar3.set(Experience)
    Emp_ID=EmployeeId.get()
    strvar4.set(Emp_ID)
    education=EmployeeEducation.get()
    strvar5.set(education)
    Email=EmployeeEmail.get()
    strvar6.set(Email)
    address=EmployeeAddress.get()
    strvar7.set(address)
    sum=float(jansal.get())+float(febsal.get())+float(Marsal.get())+float(Aprsal.get())+float(Maysal.get())+float(Junesal.get())+float(Julysal.get())+float(Augsal.get())+float(Sepsal.get())+float(Octsal.get())+float(Novsal.get())+float(Decsal.get())
    salary.set(sum)
    sum1=float(janPT.get())+float(febPT.get())+float(MarPT.get())+float(AprPT.get())+float(MayPT.get())+float(JunePT.get())+float(JulyPT.get())+float(AugPT.get())+float(SepPT.get())+float(OctPT.get())+float(NovPT.get())+float(DecPT.get())
    PT.set(sum1)
    Leav=int(janleave.get())+int(febleave.get())+int(Marleave.get())+int(Aprleave.get())+int(Mayleave.get())+int(Juneleave.get())+int(Julyleave.get())+int(Augleave.get())+int(Sepleave.get())+int(Octleave.get())+int(Novleave.get())+int(Decleave.get())
    leave.set(Leav)
    Jan_sal=round(((30-(int(janleave.get())))*(float(jansal.get()))/30)-(float(janPT.get())),2)
    paid.set(Jan_sal)
    Feb_sal=round((30-(int(febleave.get())))*(float(febsal.get()))/30-(float(febPT.get())),2)
    P2.set(Feb_sal)
    Mar_sal=round((30-(int(Marleave.get())))*(float(Marsal.get()))/30-(float(MarPT.get())),2)
    P3.set(Mar_sal)
    Apr_sal=round((30-(int(Aprleave.get())))*(float(Aprsal.get()))/30-(float(AprPT.get())),2)
    P4.set(Apr_sal)
    May_sal=round((30-(int(Mayleave.get())))*(float(Maysal.get()))/30-(float(MayPT.get())),2)
    P5.set(May_sal)
    June_sal=round((30-(int(Juneleave.get())))*(float(Junesal.get()))/30-(float(JunePT.get())),2)
    P6.set(June_sal)
    July_sal=round((30-(int(Julyleave.get())))*(float(Julysal.get()))/30-(float(JulyPT.get())),2)        
    P7.set(July_sal)
    Aug_sal=round((30-(int(Augleave.get())))*(float(Augsal.get()))/30-(float(AugPT.get())),2)
    P8.set(Aug_sal)
    sep_sal=round((30-(int(Sepleave.get())))*(float(Sepsal.get()))/30-(float(SepPT.get())),2)
    P9.set(sep_sal)
    Oct_sal=round((30-(int(Octleave.get())))*(float(Octsal.get()))/30-(float(OctPT.get())),2)
    P10.set(Oct_sal)
    Nov_sal=round((30-(int(Novleave.get())))*(float(Novsal.get()))/30-(float(NovPT.get())),2)
    P11.set(Nov_sal)
    Dec_sal=round((30-(int(Decleave.get())))*(float(Decsal.get()))/30-(float(DecPT.get())),2)
    P12.set(Dec_sal)
    sum3=float(paid.get())+float(P2.get())+float(P3.get())+float(P4.get())+float(P5.get())+float(P6.get())+float(P7.get())+float(P8.get())+float(P9.get())+float(P10.get())+float(P11.get())+float(P12.get())
    total_sal.set(sum3)
window.title("Employee Record Management")
window.geometry("1800x1500")
Label(window,text="Enter your Employee Full Name:").grid(row=1,column=0)
Label(window,text="Enter your Employee Ph.Number:").grid(row=2,column=0)
Label(window,text="Enter your Employee Department:").grid(row=3,column=0)
Label(window,text="Enter your Employee Experience:").grid(row=4,column=0)
EmployeeFullName=Entry(window,fg="green",borderwidth=1,relief="solid")
EmployeeFullName.grid(row=1,column=1)
EmployeePhNumber=Entry(window,fg="green",borderwidth=1,relief="solid")
EmployeePhNumber.grid(row=2,column=1)
EmployeeDepartment=Entry(window,fg="green",borderwidth=1,relief="solid")
EmployeeDepartment.grid(row=3,column=1)
EmployeeExperience=Entry(window,fg="green",borderwidth=1,relief="solid")
EmployeeExperience.grid(row=4,column=1)
Label(window,text="").grid(row=5,column=0)
Label(window,text="Enter Jan salary Amount:").grid(row=6,column=0)
Label(window,text="Enter Feb salary Amount:").grid(row=7,column=0)
Label(window,text="Enter Mar salary Amount:").grid(row=8,column=0)
Label(window,text="Enter Apr salary Amount:").grid(row=9,column=0)
Label(window,text="Enter May salary Amount:").grid(row=10,column=0)
Label(window,text="Enter June salary Amount:").grid(row=11,column=0)
Label(window,text="Enter July salary Amount:").grid(row=12,column=0)
Label(window,text="Enter Aug salary Amount:").grid(row=13,column=0)
Label(window,text="Enter Sep salary Amount:").grid(row=14,column=0)
Label(window,text="Enter Oct salary Amount:").grid(row=15,column=0)
Label(window,text="Enter Nov salary Amount:").grid(row=16,column=0)
Label(window,text="Enter Dec salary Amount:").grid(row=17,column=0)
jansal=Entry(window,fg="green",borderwidth=1,relief="solid")
jansal.grid(row=6,column=1)
febsal=Entry(window,fg="green",borderwidth=1,relief="solid")
febsal.grid(row=7,column=1)
Marsal=Entry(window,fg="green",borderwidth=1,relief="solid")
Marsal.grid(row=8,column=1)
Aprsal=Entry(window,fg="green",borderwidth=1,relief="solid")
Aprsal.grid(row=9,column=1)
Maysal=Entry(window,fg="green",borderwidth=1,relief="solid")
Maysal.grid(row=10,column=1)
Junesal=Entry(window,fg="green",borderwidth=1,relief="solid")
Junesal.grid(row=11,column=1)
Julysal=Entry(window,fg="green",borderwidth=1,relief="solid")
Julysal.grid(row=12,column=1)
Augsal=Entry(window,fg="green",borderwidth=1,relief="solid")
Augsal.grid(row=13,column=1)
Sepsal=Entry(window,fg="green",borderwidth=1,relief="solid")
Sepsal.grid(row=14,column=1)
Octsal=Entry(window,fg="green",borderwidth=1,relief="solid")
Octsal.grid(row=15,column=1)
Novsal=Entry(window,fg="green",borderwidth=1,relief="solid")
Novsal.grid(row=16,column=1)
Decsal=Entry(window,fg="green",borderwidth=1,relief="solid")
Decsal.grid(row=17,column=1)
Label(window,text="Enter Jan Leaves Amount:").grid(row=6,column=2)
Label(window,text="Enter Feb Leaves Amount:").grid(row=7,column=2)
Label(window,text="Enter Mar Leaves Amount:").grid(row=8,column=2)
Label(window,text="Enter Apr Leaves Amount:").grid(row=9,column=2)
Label(window,text="Enter May Leaves Amount:").grid(row=10,column=2)
Label(window,text="Enter June Leaves Amount:").grid(row=11,column=2)
Label(window,text="Enter July Leaves Amount:").grid(row=12,column=2)
Label(window,text="Enter Aug Leaves Amount:").grid(row=13,column=2)
Label(window,text="Enter Sep Leaves Amount:").grid(row=14,column=2)
Label(window,text="Enter Oct Leaves Amount:").grid(row=15,column=2)
Label(window,text="Enter Nov Leaves Amount:").grid(row=16,column=2)
Label(window,text="Enter Dec Leaves Amount:").grid(row=17,column=2)
janleave=Entry(window,fg="green",borderwidth=1,relief="solid")
janleave.grid(row=6,column=3)
febleave=Entry(window,fg="green",borderwidth=1,relief="solid")
febleave.grid(row=7,column=3)
Marleave=Entry(window,fg="green",borderwidth=1,relief="solid")
Marleave.grid(row=8,column=3)
Aprleave=Entry(window,fg="green",borderwidth=1,relief="solid")
Aprleave.grid(row=9,column=3)
Mayleave=Entry(window,fg="green",borderwidth=1,relief="solid")
Mayleave.grid(row=10,column=3)
Juneleave=Entry(window,fg="green",borderwidth=1,relief="solid")
Juneleave.grid(row=11,column=3)
Julyleave=Entry(window,fg="green",borderwidth=1,relief="solid")
Julyleave.grid(row=12,column=3)
Augleave=Entry(window,fg="green",borderwidth=1,relief="solid")
Augleave.grid(row=13,column=3)
Sepleave=Entry(window,fg="green",borderwidth=1,relief="solid")
Sepleave.grid(row=14,column=3)
Octleave=Entry(window,fg="green",borderwidth=1,relief="solid")
Octleave.grid(row=15,column=3)
Novleave=Entry(window,fg="green",borderwidth=1,relief="solid")
Novleave.grid(row=16,column=3)
Decleave=Entry(window,fg="green",borderwidth=1,relief="solid")
Decleave.grid(row=17,column=3)
Label(window,text="Enter Jan PT Amount:").grid(row=6,column=4)
Label(window,text="Enter Feb PT Amount:").grid(row=7,column=4)
Label(window,text="Enter Mar PT Amount:").grid(row=8,column=4)
Label(window,text="Enter Apr PT Amount:").grid(row=9,column=4)
Label(window,text="Enter May PT Amount:").grid(row=10,column=4)
Label(window,text="Enter June PT Amount:").grid(row=11,column=4)
Label(window,text="Enter July PT Amount:").grid(row=12,column=4)
Label(window,text="Enter Aug PT Amount:").grid(row=13,column=4)
Label(window,text="Enter Sep PT Amount:").grid(row=14,column=4)
Label(window,text="Enter Oct PT Amount:").grid(row=15,column=4)
Label(window,text="Enter Nov PT Amount:").grid(row=16,column=4)
Label(window,text="Enter Dec PT Amount:").grid(row=17,column=4)
janPT=Entry(window,fg="green",borderwidth=1,relief="solid")
janPT.grid(row=6,column=5)
febPT=Entry(window,fg="green",borderwidth=1,relief="solid")
febPT.grid(row=7,column=5)
MarPT=Entry(window,fg="green",borderwidth=1,relief="solid")
MarPT.grid(row=8,column=5)
AprPT=Entry(window,fg="green",borderwidth=1,relief="solid")
AprPT.grid(row=9,column=5)
MayPT=Entry(window,fg="green",borderwidth=1,relief="solid")
MayPT.grid(row=10,column=5)
JunePT=Entry(window,fg="green",borderwidth=1,relief="solid")
JunePT.grid(row=11,column=5)
JulyPT=Entry(window,fg="green",borderwidth=1,relief="solid")
JulyPT.grid(row=12,column=5)
AugPT=Entry(window,fg="green",borderwidth=1,relief="solid")
AugPT.grid(row=13,column=5)
SepPT=Entry(window,fg="green",borderwidth=1,relief="solid")
SepPT.grid(row=14,column=5)
OctPT=Entry(window,fg="green",borderwidth=1,relief="solid")
OctPT.grid(row=15,column=5)
NovPT=Entry(window,fg="green",borderwidth=1,relief="solid")
NovPT.grid(row=16,column=5)
DecPT=Entry(window,fg="green",borderwidth=1,relief="solid")
DecPT.grid(row=17,column=5)
Label(window,text="Paid Jan salary:").grid(row=6,column=6)
Label(window,text="Paid Feb salary:").grid(row=7,column=6)
Label(window,text="Paid Mar salary:").grid(row=8,column=6)
Label(window,text="Paid Apr salary:").grid(row=9,column=6)
Label(window,text="Paid May salary:").grid(row=10,column=6)
Label(window,text="Paid June salary:").grid(row=11,column=6)
Label(window,text="Paid July salary:").grid(row=12,column=6)
Label(window,text="Paid Aug salary:").grid(row=13,column=6)
Label(window,text="Paid Sep salary:").grid(row=14,column=6)
Label(window,text="Paid Oct salary:").grid(row=15,column=6)
Label(window,text="Paid Nov salary:").grid(row=16,column=6)
Label(window,text="Paid Dec salary:").grid(row=17,column=6)
Label(window,text="Enter your Employee Id:").grid(row=1,column=4)
Label(window,text="Enter your Employee Email:").grid(row=2,column=4)
Label(window,text="Enter your Employee Address:").grid(row=3,column=4)
Label(window,text="Enter your Employee Education:").grid(row=4,column=4)
EmployeeId=Entry(window,fg="green",borderwidth=1,relief="solid")
EmployeeId.grid(row=1,column=5)
EmployeeEmail=Entry(window,fg="green",borderwidth=1,relief="solid")
EmployeeEmail.grid(row=2,column=5)
EmployeeAddress=Entry(window,fg="green",borderwidth=1,relief="solid")
EmployeeAddress.grid(row=3,column=5)
EmployeeEducation=Entry(window,fg="green",borderwidth=1,relief="solid")
EmployeeEducation.grid(row=4,column=5)
# Label(window,text="--------------------------------------------------------------------------").grid(row=17,column=0)
Label(window,fg="grey10",text="----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------").grid(row=18,columnspan=8)
Label(window,text="Employee Full Name:").grid(row=19,column=0)
Label(window,text="Employee Department:").grid(row=20,column=0)
Label(window,text="Employee Id:").grid(row=19,column=2)
Label(window,text="Employee Experience:").grid(row=20,column=2)
Label(window,text="Employee phone Number:").grid(row=19,column=4)
Label(window,text="Employee Education:").grid(row=20,column=4)
Label(window,text="Employee Email:").grid(row=19,column=6)
Label(window,text="Employee Address:").grid(row=20,column=6)
Label(window,text="").grid(row=21,column=0)
Label(window,text="").grid(row=22,column=0)
Label(window,text="Total Financial Year Amount:").grid(row=23,column=0)
Label(window,text="Total Number of Leaves:").grid(row=23,column=2)
Label(window,text="Total PT Amount Debited:").grid(row=23,column=4)
Label(window,text="Total Paid salary:").grid(row=23,column=6)
Label(window,text="").grid(row=24,column=0)
Button(window,text="GO",command=Employee_Details,).grid(row=25,column=3)
Label(window,fg="green",text="",textvariable=strvar).grid(row=19,column=1)
Label(window,fg="green",text="",textvariable=strvar1).grid(row=19,column=5)
Label(window,fg="green",text="",textvariable=strvar2).grid(row=20,column=1)
Label(window,fg="green",text="",textvariable=strvar3).grid(row=20,column=3)
Label(window,fg="green",text="",textvariable=strvar4).grid(row=19,column=3)
Label(window,fg="green",text="",textvariable=strvar5).grid(row=20,column=5)
Label(window,fg="green",text="",textvariable=strvar6).grid(row=19,column=7)
Label(window,fg="green",text="",textvariable=strvar7).grid(row=20,column=7 )
Label(window,fg="green",text="",textvariable=salary).grid(row=23,column=1)
Label(window,fg="green",text="",textvariable=PT).grid(row=23,column=5)
Label(window,fg="green",text="",textvariable=leave).grid(row=23,column=3)
Label(window,fg="green",text="",textvariable=paid).grid(row=6,column=7)
Label(window,fg="green",text="",textvariable=P2).grid(row=7,column=7)
Label(window,fg="green",text="",textvariable=P3).grid(row=8,column=7)
Label(window,fg="green",text="",textvariable=P4).grid(row=9,column=7)
Label(window,fg="green",text="",textvariable=P5).grid(row=10,column=7)
Label(window,fg="green",text="",textvariable=P6).grid(row=11,column=7)
Label(window,fg="green",text="",textvariable=P7).grid(row=12,column=7)
Label(window,fg="green",text="",textvariable=P8).grid(row=13,column=7 )
Label(window,fg="green",text="",textvariable=P9).grid(row=14,column=7)
Label(window,fg="green",text="",textvariable=P10).grid(row=15,column=7)
Label(window,fg="green",text="",textvariable=P11).grid(row=16,column=7)
Label(window,fg="green",text="",textvariable=P12).grid(row=17,column=7)
Label(window,fg="green",text="",textvariable=total_sal).grid(row=23,column=7)
mainloop()