from tkinter import *
root=Tk()
N=StringVar()
R=StringVar()
E=StringVar()
B=StringVar()
S=StringVar()
J=StringVar()
P=StringVar()
D=StringVar()
C=StringVar()
marks=StringVar()
total=StringVar()
grade1=StringVar()
grade2=StringVar()
grade1=StringVar()
def Student_details():
    name=Student_name.get()
    N.set(name)
    roll_name=Student_Roll.get()
    R.set(roll_name)
    Email=Student_Email.get()
    E.set(Email)
    branch=Student_Branch.get()
    B.set(branch)
    sec=Student_section.get()
    S.set(sec)
    java=Student_Java.get()
    J.set(java)
    python=Student_Python.get()
    P.set(python)
    Data=Student_Database.get()
    D.set(Data)
    C_prog=Student_C.get()
    C.set(C_prog)
    sum=int(Student_Java.get())+int(Student_Python.get())+int(Student_Database.get())+int(Student_C.get())
    average=(float(sum/4))
    marks.set(average)
    total.set(sum)
    if average>=95:
        a="A+    PASS"
    elif average>90<95:
        a="A     PASS"
    elif average>80<85:
        a="B+    PASS"
    elif average>70<75:
        a="B     PASS"
    elif average>60<65:
        a="PASS  need more practice"
    else:
        a="F     FAIL"
    grade1.set(a)
root.title("Student Records")
root.geometry("1000x1000")
Label(root,fg="grey10",text="---------Creating Student Information-------------------------------------------------------------------------------------------------------------------------------------------------").grid(row=0,columnspan=9)
Label(root,text="").grid(row=1,column=0)
Label(root,text="Enter student Name:").grid(row=2,column=0)
Label(root,text="").grid(row=3,column=0)
Label(root,text="Enter student Roll Number:").grid(row=4,column=0)
Label(root,text="").grid(row=5,column=0)
Label(root,text="Enter student Email Id:").grid(row=6,column=0)
Label(root,text="").grid(row=7,column=0)
Label(root,text="Enter student Branch:").grid(row=8,column=0)
Label(root,text="").grid(row=9,column=0)
Label(root,text="Enter student section:").grid(row=10,column=0)
Label(root,text="").grid(row=11,column=0)
Label(root,text="Enter student Java Marks:").grid(row=12,column=0)
Label(root,text="").grid(row=13,column=0)
Label(root,text="Enter student python Marks:").grid(row=14,column=0)
Label(root,text="").grid(row=15,column=0)
Label(root,text="Enter student Database Marks:").grid(row=16,column=0)
Label(root,text="").grid(row=17,column=0)
Label(root,text="Enter student C++ Marks:").grid(row=18,column=0)
Student_name=Entry(root,borderwidth=1,relief="solid")
Student_name.grid(row=2,column=2)
Student_Roll=Entry(root,borderwidth=1,relief="solid")
Student_Roll.grid(row=4,column=2)
Student_Email=Entry(root,borderwidth=1,relief="solid")
Student_Email.grid(row=6,column=2)
Student_Branch=Entry(root,borderwidth=1,relief="solid")
Student_Branch.grid(row=8,column=2)
Student_section=Entry(root,borderwidth=1,relief="solid")
Student_section.grid(row=10,column=2)
Student_Java=Entry(root,borderwidth=1,relief="solid")
Student_Java.grid(row=12,column=2)
Student_Python=Entry(root,borderwidth=1,relief="solid")
Student_Python.grid(row=14,column=2)
Student_Database=Entry(root,borderwidth=1,relief="solid")
Student_Database.grid(row=16,column=2)
Student_C=Entry(root,borderwidth=1,relief="solid")
Student_C.grid(row=18,column=2)
Label(root,text="").grid(row=19,column=0)
Button(root,text="submit",borderwidth=1,relief="solid",command=Student_details).grid(row=20,column=1)
Label(root,text="").grid(row=21,column=0)
Label(root,fg="grey10",text="---------Student Details-------------------------------------------------------------------------------------------------------------------------------------------------").grid(row=22,columnspan=9)
Label(root,text="").grid(row=23,column=0)
Label(root,text="Student Name :").grid(row=24,column=0)
Label(root,text="Student Roll Number :").grid(row=24,column=2)
Label(root,text="Student Email Id :").grid(row=24,column=4)
Label(root,text="").grid(row=25,column=0)
Label(root,text="Student Branch :").grid(row=26,column=0)
Label(root,text="Student Section :").grid(row=26,column=2)
Label(root,text="").grid(row=27,column=0)
Label(root,fg="grey10",text="---------Student Marks Details-------------------------------------------------------------------------------------------------------------------------------------------------").grid(row=28,columnspan=9)
Label(root,text="").grid(row=29,column=0)
Label(root,text="Student Java Marks :").grid(row=30,column=0)
Label(root,text="Student Python Marks :").grid(row=30,column=2)
Label(root,text="Student  Database Marks :").grid(row=30,column=4)
Label(root,text="").grid(row=31,column=0)
Label(root,text="Student  C++ Marks :").grid(row=32,column=0)
Label(root,text="").grid(row=33,column=0)
Label(root,fg="grey10",text="---------Student Total & percentage-------------------------------------------------------------------------------------------------------------------------------------------------").grid(row=34,columnspan=9)
Label(root,text="").grid(row=35,column=0)
Label(root,text="Student Total Marks :").grid(row=36,column=0)
Label(root,text="Student Percentage is :").grid(row=36,column=2)
Label(root,text="GRADE ",borderwidth=1,relief="solid").grid(row=36,column=5)
Label(root,fg="blue",textvariable=N).grid(row=24,column=1)
Label(root,fg="blue",textvariable=R).grid(row=24,column=3)
Label(root,fg="blue",textvariable=E).grid(row=24,column=5)
Label(root,fg="blue",textvariable=B).grid(row=26,column=1)
Label(root,fg="blue",textvariable=S).grid(row=26,column=3)
Label(root,fg="blue",textvariable=J).grid(row=30,column=1)
Label(root,fg="blue",textvariable=P).grid(row=30,column=3)
Label(root,fg="blue",textvariable=D).grid(row=30,column=5)
Label(root,fg="blue",textvariable=C).grid(row=32,column=1)
Label(root,fg="blue",textvariable=marks).grid(row=36,column=3)
Label(root,fg="blue",textvariable=total).grid(row=36,column=1)
Label(root,fg="Green",textvariable=grade1).grid(row=36,column=6)
# Label(root,fg="blue",textvariable=grade1).grid(row=36,column=6)
mainloop()